library(distObj)

chunk1 	<- distObj:::addTestChunk("chunk1", 1:5)
chunk2 	<- distObj:::addTestChunk("chunk2", 6:10)
chunk3 	<- distObj:::addTestChunk("chunk3", 11:15)
chunkA 	<- distObj:::addTestChunk("chunkA", 1:3)
chunkB 	<- distObj:::addTestChunk("chunkB", 1:5)
chunkC 	<- distObj:::addTestChunk("chunkC", 9:12)
chunkD 	<- distObj:::addTestChunk("chunkD", 13:18)
chunkE 	<- distObj:::addTestChunk("chunkE", 17:19)
chunkF 	<- distObj:::addTestChunk("chunkF", 3:18)
chunkG 	<- distObj:::addTestChunk("chunkG", 8:18)
chunkH 	<- distObj:::addTestChunk("chunkH", 1:38)
chunkI 	<- distObj:::addTestChunk("chunkI", 2:16)
chunkJ 	<- distObj:::addTestChunk("chunkJ", 2:15)
chunkK 	<- distObj:::addTestChunk("chunkK", 1:16)
chunkL 	<- distObj:::addTestChunk("chunkL", 4:25)
chunkM 	<- distObj:::addTestChunk("chunkL", 1L)
chunkN 	<- distObj:::addTestChunk("chunkL", 4L)

distObj1<- distObj:::makeDistObj(list(chunk1, chunk2, chunk3))
distObj2<- distObj:::makeDistObj(list(chunkH))
distObj3<- distObj:::makeDistObj(list(chunkA))
