combine		<- function(...) UseMethod("combine", ..1)
delete		<- function(x, ...) UseMethod("delete", x)
from		<- function(x, ...) UseMethod("from", x)
fun		<- function(x, ...) UseMethod("fun", x)
host		<- function(x, ...) UseMethod("host", x)
insert		<- function(x, ...) UseMethod("insert", x)
size		<- function(...) UseMethod("size", ..1)
distribute	<- function(arg, target) UseMethod("distribute", target)
target		<- function(x, ...) UseMethod("target", x)
to		<- function(x, ...) UseMethod("to", x)
emerge		<- function(arg, target) UseMethod("emerge", arg)

`from<-`        <- function(x, value) UseMethod("from<-", x)
`host<-`        <- function(x, value) UseMethod("host<-", x)
`insert<-`        <- function(x, value) UseMethod("insert<-", x)
`port<-`        <- function(x, value) UseMethod("port<-", x)
`size<-`        <- function(x, value) UseMethod("size<-", x)
`to<-`          <- function(x, value) UseMethod("to<-", x)

port 		<- function(x, ...) {
	if (missing(x)) return(.Call(C_port))
	UseMethod("port", x)
}

# masking
args		<- function(...) UseMethod("args", ..1)
args.default	<- function(...) base::args(...)
table		<- function(...) UseMethod("table", ..1)
table.default	<- function(...) base::table(...)
nrow		<- function(x) UseMethod("nrow", x)
nrow.default	<- function(x) base::nrow(x)
ncol		<- function(x) UseMethod("ncol", x)
ncol.default	<- function(x) base::ncol(x)
colnames	<- function(x, ...) UseMethod("colnames", x)
colnames.default<- function(x, ...) base::colnames(x, ...)
